name: Deploy PHP App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2' # Adjust as needed

    - name: Install dependencies
      run: composer install

    - name: Set Environment Variables
      env:
        HOST: ${{ secrets.HOST }}
        FTPUSERNAME: ${{ secrets.FTPUSERNAME }}
        FTPPASSWORD: ${{ secrets.FTPPASSWORD }}
        DBNAME1: ${{ secrets.DBNAME1 }}
        DBNAME2: ${{ secrets.DBNAME2 }}
      run: |
        echo "<?php" > config.php
        echo "\$host = getenv('HOST');" >> config.php
        echo "\$username = getenv('FTPUSERNAME');" >> config.php
        echo "\$password = getenv('FTPPASSWORD');" >> config.php
        echo "\$dbname1 = getenv('DBNAME1');" >> config.php
        echo "\$dbname2 = getenv('DBNAME2');" >> config.php